site_name: Unity-docs
# site_url:

#repo_url: https://github.com/BHFFMMST/unity-docs
#repo_name: BHFFMMST/unity-docs

#
# Theme Settings
#


plugins:
  - search
  - mermaid2

theme:
  name: material
  logo: assets/images/bhff-favicon.png
  favicon: assets/images/bhff-favicon.png

  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.tabs
    - navigation.sections
    - navigation.path
    # - navigation.tabs.sticky
    # - navigation.expand

    # Table of contents
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
    - toc.integrate

    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#setting-up-site-search    - search.suggest
    - search.suggest
    - search.highlight

    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: bhff
      toggle:
        icon: material/weather-sunny
        name: Prebaci na tamni mod

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Prebaci na svijetli mod

#
# Extra Settings
#
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/BHFFMMST
      name: BHFFMMST GitHub Org

extra_css:
  - assets/css/extra.css

#
# Extensions
#
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

  

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - attr_list

  - admonition
  - footnotes

#
# Navigation
# https://www.mkdocs.org/user-guide/configuration/#nav
#

nav:
  - Uvod: index.md
  - Igra: 
    - Kretanje: content/Igra/Kretanje/index.md
    - Tilemap: content/Igra/Tilemap/index.md
    - Animacija: content/Igra/Animacija/index.md
    - Game Mechanics 1: content/Igra/GM1/index.md
    - Game Mechanics 2: content/Igra/GM2/index.md
    - Game Mechanics 3: content/Igra/GM3/index.md
      

